############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Short CV"
url = "/about"
weight = 2

[[main]]
name = "Publications"
url = "/blog"
weight = 3


[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
